### ISSUE TITLE
running  otel/opentelemetry-ebpf-profiler-dev:latest  ended with an error (/bin/bash: -c: option requires an argument)

### ISSUE THREAD

**Issue by tomert-alma** [open-telemetry/opentelemetry-ebpf-profiler#309]
Im trying to run this yaml file,  and this is the error I see `│ /bin/bash: -c: option requires an argument `
what am I missing, what should be the entrypoint of the docker? 
any help will be highly appreciated 

````
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: otel-ebpf-profiler
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: otel-ebpf-profiler
  template:
    metadata:
      labels:
        app: otel-ebpf-profiler
    spec:
      hostPID: true
      containers:
      - name: ebpf-profiler
        image: otel/opentelemetry-ebpf-profiler-dev:latest
        securityContext:
          privileged: true
        volumeMounts:
        - name: lib-modules
          mountPath: /lib/modules
          readOnly: true
        - name: sys-fs-bpf
          mountPath: /sys/fs/bpf
      volumes:
      - name: lib-modules
        hostPath:
          path: /lib/modules
      - name: sys-fs-bpf
        hostPath:
          path: /sys/fs/bpf
```
