### ISSUE TITLE
cannot start up ebpf-profiler

### ISSUE THREAD

**Issue by lingpeng0314** [open-telemetry/opentelemetry-ebpf-profiler#315]
Code: latest master branch code
Step:
1. run the pod using image otel/opentelemetry-ebpf-profiler-dev:latest
2. make all based on master code
3. run command `./ebpf-profiler -collection-agent=127.0.0.1:11000 -disable-tls`

Error:
INFO[0000] Starting OTEL profiling agent v0.0.0 (revision main-2698137c, build timestamp 1737425070) 
INFO[0000] Interpreter tracers: perl,php,python,hotspot,ruby,v8,dotnet 
INFO[0000] Found offsets: task stack 0x20, pt_regs 0x3f58, tpbase 0x1468 
INFO[0000] Supports generic eBPF map batch operations   
INFO[0000] Supports LPM trie eBPF map batch operations  
INFO[0000] eBPF tracer loaded                           
INFO[0000] Attached tracer program                      
ERRO[0000] Failed to start agent controller: failed to attach scheduler monitor: failed to configure tracepoint on tracer.hookPoint{group:"sched", name:"sched_process_exit"}: neither debugfs nor tracefs are mounted

Pls. help point the way to resolve this.

**Comment by lingpeng0314** [comment]
@christos68k Could you pls. help?

**Comment by florianl** [comment]
The problem is `neither debugfs nor tracefs are mounted`.
Can you provide the output for the following command to check, if these special filesystems are mounted?
```
$ mount | egrep 'debugfs|tracefs'
```


In addition, can you please provide the output for the configuration options for the following Kernel parameters?

```
$ uname -r
$ grep CONFIG_FTRACE /boot/config-$(uname -r)
$ grep CONFIG_TRACEPOINTS /boot/config-$(uname -r)
```

Are you running the eBPF profiler in a special (cloud?) environment?

**Comment by lingpeng0314** [comment]
Output for commands:
`uname -r
5.15.0-26-generic
root@ebpf-lynn-79f98fb799-4bxnf:/agent# grep CONFIG_FTRACE /boot/config-$(uname -r)
grep: /boot/config-5.15.0-26-generic: No such file or directory
root@ebpf-lynn-79f98fb799-4bxnf:/agent# grep CONFIG_TRACEPOINTS /boot/config-$(uname -r)
grep: /boot/config-5.15.0-26-generic: No such file or directory
root@ebpf-lynn-79f98fb799-4bxnf:/agent# mount | egrep 'debugfs|tracefs'
`

And i am running the eBPR profiler as an agent pod in K8s env.

Could you pls. provide the steps how i can make it working normally?

**Comment by florianl** [comment]
It looks like the relevant special file systems are not available.

Are you running the eBPF profiler on a node or pod level? It is recommended to run the eBPF profiler as daemonset. 
The configuration file of the daemonset should also provide access to debugfs. Here are some parts of such a configuration:

```
kind: DaemonSet
[..]
    spec:
      hostPID: true
          securityContext:
            procMount: "Unmasked"
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
          volumeMounts:
            - name: debugfs
              mountPath: /sys/kernel/debug
              readOnly: true
      volumes:
        - name: debugfs
          hostPath:
            path: /sys/kernel/debug
            type: Directory
```
