### ISSUE TITLE
Profiling for specific process by labels, not all node processes

### ISSUE THREAD

**Issue by lingpeng0314** [open-telemetry/opentelemetry-ebpf-profiler#358]
I am not sure if this feature is reasonable for this project, may be more proper when migrate this profiler into openTelemetry collector as profiling agent.

We plan to adopt continuous profiling for internal use. And the common use case is to select some specific pods to obtain profiling data instead of all kinds of processes in K8s node.

Invested several agents like Grafana Alloy/Parca/Pixie, all of them support the feature that only profiling specific pods. And as we move eBPF profiler into collector as agent, this should be a very reasonable requirement right?

**Comment by lingpeng0314** [comment]
Look forward to the integration into OTel collector very much.

**Comment by lingpeng0314** [comment]
@florianl Do we have roadmap for when integrate the profiler into OTel collector?

**Comment by vjsamuel** [comment]
@florianl , to your comment on limiting it to post processing, it would add overhead on the node given it will profile every single process. is it not possible to filter down to specific pods?

**Comment by florianl** [comment]
> Do we have roadmap for when integrate the profiler into OTel collector?

With the merge of https://github.com/open-telemetry/opentelemetry-collector-releases/pull/908 one big step was achieved to make profiling part of OTel collector. Profiling is still considered not stable in Open Telemetry, as there is still work ongoing. As far as I know, there is no fixed roadmap.

> [..] it would add overhead on the node given it will profile every single process. is it not possible to filter down to specific pods?

eBPF profiler is designed as whole system profiler. Benchmarks as real world deployments show, that it's overhead on profiling all processes is minimal and negligible. Adding filtering on the eBPF level would introduce some noticeable complexity and maybe race conditions.

**Comment by hanshal101** [comment]
Hi @florianl ,
I totally agree with @lingpeng0314  that limiting profiling to specific pods or processes would be a game-changer for many companies and organizations. It's a very common use case, especially when scaling in Kubernetes environments, where profiling everything at the node level adds unnecessary overhead and complexity.
I'm really excited to see how the community will continue to enhance this feature.
I would love to help contribute to this effort, whether it's by adding support for filtering based on labels or improving post-processing to make it more efficient. This is a feature that can really benefit the whole ecosystem, and I believe it's worth exploring further to reduce overhead and optimize profiling for specific workloads.

Looking forward to collaborating on this! Let me know if there’s a place where I can get started with a contribution. Or let me know how I can be useful here!
Thanks!

**Comment by florianl** [comment]
Please be aware that profiling is not aware of elements or information that you request to filter on. External OTel components, like the `resourcedetection` or `k8sattributes` OTel processors, enrich the data in a way that filter on these concepts are even possible.
Using these components, it is possible to filter profiling as requested.

But as the majority level of profiling is still under development, there is no full ottl or otlp support in OTel collector yet. But we are working on it https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/40489

**Comment by hanshal101** [comment]
> Please be aware that profiling is not aware of elements or information that you request to filter on. External OTel components, like the `resourcedetection` or `k8sattributes` OTel processors, enrich the data in a way that filter on these concepts are even possible. Using these components, it is possible to filter profiling as requested.
> 
> But as the majority level of profiling is still under development, there is no full ottl or otlp support in OTel collector yet. But we are working on it [open-telemetry/opentelemetry-collector-contrib#40489](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/40489)

Cool, thanks for letting me know. I am really confused as I can't find any relevant docs which provides some information/examples on using the k8sattributes with the `otlp/profiles` on the collector-contrib. Can you please share if you have any!

**Comment by florianl** [comment]
Here is an example config where `k8sattributes` enriches profiling information.

<details>
<summary>config.yaml using profiling with k8sattributes</summary>

```
receivers:
  profiling:
    SamplesPerSecond: 19

processors:
  k8sattributes:
    auth_type: "serviceAccount"
    passthrough: false
    filter:
      # only retrieve pods running on the same node as the collector
      node_from_env_var: KUBERNETES_NODE_NAME
    extract:
      # The attributes provided in 'metadata' will be added to associated resources
      metadata:
        - k8s.pod.name
        - k8s.pod.uid
        - k8s.deployment.name
        - k8s.namespace.name
        - k8s.node.name
        - k8s.pod.start_time
        - service.namespace
        - service.name
        - service.version
        - service.instance.id
      otel_annotations: true 
    pod_association:
      - sources:
          # This rule associates all resources containing the 'container.id' attribute with the matching pods. If this attribute is not present in the resource, this rule will not be able to find the matching pod.
          - from: resource_attribute
            name: container.id

exporters:
  debug:
    verbosity: detailed

service:
  pipelines:
    profiles:
      receivers: [ profiling ]
      processors: [ k8sattributes]
      exporters: [ debug ]
```

</details>

**Comment by hanshal101** [comment]
> Here is an example config where `k8sattributes` enriches profiling information.
> 
> config.yaml using profiling with k8sattributes

Amazing, thanks for helping me out here. I have another question this is my config file:
```yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

processors:
  k8sattributes:
    auth_type: kubeConfig
    passthrough: false
    filter:
      node_from_env_var: KUBERNETES_NODE_NAME
    extract:
      metadata:
        - k8s.pod.name
        - k8s.pod.uid
        - k8s.deployment.name
        - k8s.namespace.name
        - k8s.node.name
        - k8s.pod.start_time
        - service.namespace
        - service.name
        - service.version
        - service.instance.id
      otel_annotations: true
    pod_association:
      - sources:
          - from: resource_attribute
            name: container.id

exporters:
  debug:
    verbosity: detailed
  otlp:
    endpoint: "http://pyroscope:4040"
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug]
    metrics:
      receivers: [otlp]
      exporters: [debug]
    logs:
      receivers: [otlp]
      exporters: [debug]
    profiles:
      receivers: [otlp]
      exporters: [otlp, debug]
  telemetry:
    logs:
      level: debug
```

And this is how I am deploying the collector, pyroscope and the grafana:
```yaml
services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector-config.yaml", "--feature-gates=service.profilesSupport"]
    volumes:
      - ./config/otel-collector-config.yaml:/etc/otel-collector-config.yaml
      - /home/hanshal101/.kube/config:/etc/kube/config:ro
    ports:
      - "4317:4317"
      - "4318:4318"
    environment:
      - KUBERNETES_NODE_NAME=secai-control-plane
      - KUBECONFIG=/etc/kube/config
    depends_on:
      - pyroscope

  pyroscope:
    # fixed versions for pyroscope, otel-collector, otel-profiler due to protocol changes
    image: grafana/pyroscope
    command: ["-self-profiling.disable-push=true"]
    ports:
      - "4040:4040"

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_INSTALL_PLUGINS=grafana-pyroscope-app
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
      - ./grafana-provisioning:/etc/grafana/provisioning
    ports:
      - "3000:3000"
```

I am not sure where I can find the attributes data, lets say I want to see the k8s.pod.name or k8s.pod.uid, Where I can see that?
