### ISSUE TITLE
Support PHP 8.4

### ISSUE THREAD

**Issue by rockdaboot** [open-telemetry/opentelemetry-ebpf-profiler#463]
With PHP 8.4.6 on Debian trixie, his log line is printed:
```
time="2025-05-14T15:39:19.757746293+02:00" level=error msg="Failed to load /usr/bin/php8.4 (0xcda84bb08a78326f): PHP version 8.4.6 (need >= 7.3 and < 8.4)"
```

**Comment by danielpacak** [comment]
Heya @rockdaboot - do you think I can help with this issue? I happened to play with PHP recently so should be able to verify quickly what's missing for PHP 8.4.

**Comment by florianl** [comment]
I have assigned the issue to you, @danielpacak . Happy to help, if you need assistance.

**Comment by danielpacak** [comment]
To start with an example app that everyone can refer to I'm going to use wordpress. It has container images for PHP 8.3 and PHP 8.4 so it's easy to reproduce and verify the fix.

``` yaml
services:
  wordpress:
    image: wordpress:6.8.2-php8.4-apache
    #image: wordpress:6.8.2-php8.3-apache
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
volumes:
  wordpress:
  db:
```

The ebpf-profiler works for `docker.io/library/wordpress:6.8.2-php8.3-apache`, but does not work for `docker.io/library/wordpress:6.8.2-php8.4-apache`. Let's figure what's missing.

```
------------------- New Sample -------------------
  thread.name: apache2
  process.executable.name: apache2
  process.executable.path: /usr/sbin/apache2
  process.pid: 270722
  thread.id: 270722
---------------------------------------------------
Instrumentation: php, Function: apply_filters, File: /var/www/html/wp-includes/class-wp-hook.php, Line: 321, Column: 0
Instrumentation: php, Function: apply_filters, File: /var/www/html/wp-includes/plugin.php, Line: 205, Column: 0
Instrumentation: php, Function: wp_kses_hook, File: /var/www/html/wp-includes/kses.php, Line: 948, Column: 0
Instrumentation: php, Function: wp_kses, File: /var/www/html/wp-includes/kses.php, Line: 754, Column: 0
Instrumentation: php, Function: wp_kses_split2, File: /var/www/html/wp-includes/kses.php, Line: 1155, Column: 0
Instrumentation: php, Function: _wp_kses_split_callback, File: /var/www/html/wp-includes/kses.php, Line: 1071, Column: 0
Instrumentation: php, Function: preg_replace_callback, File: , Line: 0, Column: 0
Instrumentation: php, Function: wp_kses_split, File: /var/www/html/wp-includes/kses.php, Line: 1001, Column: 0
Instrumentation: php, Function: wp_kses, File: /var/www/html/wp-includes/kses.php, Line: 756, Column: 0
Instrumentation: php, Function: wp_kses_post, File: /var/www/html/wp-includes/kses.php, Line: 2234, Column: 0
Instrumentation: php, Function: prepare_item_for_response, File: /var/www/html/wp-includes/rest-api/endpoints/class-wp-rest-pattern-directory-controller.php, Line: 199, Column: 0
Instrumentation: php, Function: get_items, File: /var/www/html/wp-includes/rest-api/endpoints/class-wp-rest-pattern-directory-controller.php, Line: 174, Column: 0
Instrumentation: php, Function: respond_to_request, File: /var/www/html/wp-includes/rest-api/class-wp-rest-server.php, Line: 1292, Column: 0
Instrumentation: php, Function: dispatch, File: /var/www/html/wp-includes/rest-api/class-wp-rest-server.php, Line: 1125, Column: 0
Instrumentation: php, Function: rest_do_request, File: /var/www/html/wp-includes/rest-api.php, Line: 586, Column: 0
Instrumentation: php, Function: _load_remote_featured_patterns, File: /var/www/html/wp-includes/block-patterns.php, Line: 276, Column: 0
Instrumentation: php, Function: get_items, File: /var/www/html/wp-includes/rest-api/endpoints/class-wp-rest-block-patterns-controller.php, Line: 108, Column: 0
Instrumentation: php, Function: respond_to_request, File: /var/www/html/wp-includes/rest-api/class-wp-rest-server.php, Line: 1292, Column: 0
Instrumentation: php, Function: dispatch, File: /var/www/html/wp-includes/rest-api/class-wp-rest-server.php, Line: 1125, Column: 0
Instrumentation: php, Function: serve_request, File: /var/www/html/wp-includes/rest-api/class-wp-rest-server.php, Line: 439, Column: 0
Instrumentation: php, Function: rest_api_loaded, File: /var/www/html/wp-includes/rest-api.php, Line: 459, Column: 0
Instrumentation: php, Function: apply_filters, File: /var/www/html/wp-includes/class-wp-hook.php, Line: 324, Column: 0
Instrumentation: php, Function: do_action, File: /var/www/html/wp-includes/class-wp-hook.php, Line: 348, Column: 0
Instrumentation: php, Function: do_action_ref_array, File: /var/www/html/wp-includes/plugin.php, Line: 565, Column: 0
Instrumentation: php, Function: parse_request, File: /var/www/html/wp-includes/class-wp.php, Line: 418, Column: 0
Instrumentation: php, Function: main, File: /var/www/html/wp-includes/class-wp.php, Line: 818, Column: 0
Instrumentation: php, Function: wp, File: /var/www/html/wp-includes/functions.php, Line: 1342, Column: 0
Instrumentation: php, Function: <top-level>, File: /var/www/html/wp-blog-header.php, Line: 16, Column: 0
Instrumentation: php, Function: <top-level>, File: /var/www/html/index.php, Line: 17, Column: 0
```
