### ISSUE TITLE
Making it easier to populate Service ID

### ISSUE THREAD

**Issue by Anthony-Tafoya** [open-telemetry/opentelemetry-ebpf-profiler#547]
Hello, 
I am running profiler version 0.115.0 on a host level for my node (so host namespace). I was wondering how feasible it would be to insert k8s metadata (service_id, pod_id, etc.) and where I would do it? I was looking into the Pyroscope code and I see they expect service_id in the samples array and I just cannot pinpoint where we would insert this information. Thank you!

**Comment by florianl** [comment]
Hi 👋 
Only starting from July, this project will start using a tagged version. Therefore, I can not assign your named version number 0.115.0 to this project or a state of it.

Generally speaking, with recent (will be part of v0.129.0) changes in OTel collector contrib it is possible to enrich k8s metadata based on `container.id`. The snippet for this configuration in the OTel config.yaml then could look like this:

```
  k8sattributes:
    auth_type: "serviceAccount"
    passthrough: false
    filter:
      node_from_env_var: KUBERNETES_NODE_NAME
    extract:
      metadata:
        - k8s.pod.name
        - k8s.pod.uid
        - k8s.deployment.name
        - k8s.namespace.name
        - k8s.node.name
        - k8s.pod.start_time
        - service.namespace
        - service.name
        - service.version
        - service.instance.id
      labels:
        - tag_name: app.label.component
          key: app.kubernetes.io/component
          from: pod
      otel_annotations: true 
    pod_association:
      - sources:
          - from: resource_attribute
            name: container.id
```

Not sure how other projects, that build on OTel eBPF profiler are using or enriching metadata.

Addendum:
With the release of v1.7.0 of the OTel Profiling signal, resource attributes moved from attributes attached to each sample to ResourceProfiles. So instead of populating each sample with these attributes, there is now a ResourceProfile per `container.id` that holds all samples related to this `container.id`.
